Hierarchical choice set
catima/catima pull request #318
Opened 2021-03-22 11:23 UTC by abstracts33d

![image](https://user-images.githubusercontent.com/16547134/111982053-c8cfe880-8b08-11eb-92f0-f1d28ac8b513.png)
![image](https://user-images.githubusercontent.com/16547134/111982074-cf5e6000-8b08-11eb-96d8-ad436887d84a.png)
![image](https://user-images.githubusercontent.com/16547134/111982097-d7b69b00-8b08-11eb-8ad6-3705cbe4e1d3.png)
![image](https://user-images.githubusercontent.com/16547134/111982142-e56c2080-8b08-11eb-96b6-3912d3a90764.png)
![image](https://user-images.githubusercontent.com/16547134/111982174-ed2bc500-8b08-11eb-9c2e-d940fa0f8093.png)
![image](https://user-images.githubusercontent.com/16547134/111982194-f61c9680-8b08-11eb-9546-89d7c6d0144c.png)
![image](https://user-images.githubusercontent.com/16547134/111982255-0896d000-8b09-11eb-99f8-7e862bc07a2c.png)
![image](https://user-images.githubusercontent.com/16547134/111982300-16e4ec00-8b09-11eb-8365-d6b5b03c3edc.png)
![image](https://user-images.githubusercontent.com/16547134/111982332-1fd5bd80-8b09-11eb-8a28-662f4f507bb5.png)
![image](https://user-images.githubusercontent.com/16547134/111982442-44319a00-8b09-11eb-9675-7c2776845314.png)
![image](https://user-images.githubusercontent.com/16547134/111982479-4f84c580-8b09-11eb-85ca-e5e011fbb957.png)
![image](https://user-images.githubusercontent.com/16547134/111982519-5b708780-8b09-11eb-9636-e98c24c3c833.png)
![image](https://user-images.githubusercontent.com/16547134/111982601-7216de80-8b09-11eb-8589-8d2b744cc8b8.png)

2021-03-22 13:38 UTC, lucaguindani commented
Merci pour la PR. Ci-dessous les quelques informations promises afin de finaliser cette feature.

En affichage liste
> Pas de hiérarchie

En affichage fiche
> Pas de hiérarchie par défaut (cachée). Si existe, possibilité de l'afficher via un bouton/icône (type https://thenounproject.com/term/hierarchy/86988/ ?). Afficher un tooltip avec "Afficher la hiérarchie" quand on passe sur l'icône.

Icône de drag & drop en mode édition de choice-set
![CleanShot 2021-03-22 at 14 11 15](https://user-images.githubusercontent.com/1675064/111994978-b5c51480-8b18-11eb-9344-40f53f79b706.png)

Un autre point: serait-il possible en mode édition de choice-set d'ajouter un badge à côté des choix liés à une sous-fiche (nom de la sous-fiche dans le badge) ? C'est une chose qui va manquer comme cette information n'est plus visible sans passer par le mode édition. Ci-dessous un exemple de badge déjà utilisé dans Catima.

![CleanShot 2021-03-22 at 14 34 28](https://user-images.githubusercontent.com/1675064/111997942-d6429e00-8b1b-11eb-8cb0-d5bec89fcc08.png)

2021-03-22 14:20 UTC, skyporter requested changes

2021-03-22 14:20 UTC, skyporter commented on app/models/choice.rb
> +    end
tout mettre dans une transaction pour assurer l'intégrité des données en cas de failed

2021-03-22 14:20 UTC, skyporter commented on app/models/choice_set.rb
> +  def ordered_choices
je nommerai ca un peu différemment, genre `choices_with_sub_choices` non ? c'est plus parlant je trouve.

2021-03-22 14:25 UTC, abstracts33d commented on app/controllers/catalog_admin/choices_controller.rb
> +    find_choice
coherence avec le reste du projet

2021-03-22 14:41 UTC, skyporter commented on app/controllers/catalog_admin/choices_controller.rb
> +    find_choice
mhh, je vois que c'est mixé dans le projet, certains controller font de before_action et (pleins) d'autres pas...

Nous faisons juste, avec un `before_action` stp.

2021-03-22 14:56 UTC, abstracts33d commented on app/controllers/catalog_admin/choices_controller.rb
> +    authorize(@choice_set)
coherence avec le reste du projet

2021-03-22 15:23 UTC, abstracts33d commented on app/models/choice_set.rb
> +  def ordered_choices
ordered_choices_with_sub_choices ? choices_with_sub_choices c est pas explicite sur le fait qu ils soient mis en ordre et .choices contient deja les enfants

2021-03-22 15:24 UTC, skyporter commented on app/models/choice_set.rb
> +  def ordered_choices
faudrait un namming qui fait comprendre qu'il y a des enfants intégrés.

2021-03-23 08:41 UTC, abstracts33d commented on app/models/choice_set.rb
> +  def ordered_choices
ordered_choices_with_sub_choices c est bon ?

2021-03-23 08:58 UTC, abstracts33d commented on app/controllers/catalog_admin/choices_controller.rb
> +    find_choice
yes

2021-03-23 08:58 UTC, abstracts33d commented on app/controllers/catalog_admin/choices_controller.rb
> +    authorize(@choice_set)
ok

2021-03-23 09:00 UTC, abstracts33d commented on app/models/choice_set.rb
> +  def ordered_choices
flat_ordered_choices

2021-03-23 09:08 UTC, abstracts33d commented on app/models/choice.rb
> +    end
yes

2021-03-23 09:14 UTC, abstracts33d commented on app/controllers/catalog_admin/choices_controller.rb
> +  end
refacto dans save_with_position

2021-03-23 14:34 UTC, skyporter approved these changes

2021-03-25 13:11 UTC, merged