#179866321 composed field
catima/catima pull request #390
Opened 2021-11-05 14:56 UTC by abstracts33d

![image](https://user-images.githubusercontent.com/16547134/140530993-01273f6b-4933-4437-9240-fda34d0c86a9.png)
![image](https://user-images.githubusercontent.com/16547134/140530628-2cc2c731-e625-47ac-8441-7f88b3e58297.png)
![image](https://user-images.githubusercontent.com/16547134/140530682-ab99386f-4f69-4bea-91d6-25e031eb915a.png)
![image](https://user-images.githubusercontent.com/16547134/140530725-8fe31d13-8d9e-40ef-910b-974db0b4c465.png)
![image](https://user-images.githubusercontent.com/16547134/140530759-dd29b748-814f-4f87-82f5-ee8b5af0f0b6.png)
![image](https://user-images.githubusercontent.com/16547134/140530809-f15fe177-0539-47f7-8ab3-49a9efe085a1.png)
![image](https://user-images.githubusercontent.com/16547134/140530842-2d97285f-4721-4b92-9ad9-4d7a8c0c2f42.png)
![image](https://user-images.githubusercontent.com/16547134/140530959-a3d25fdc-1476-47c8-980b-84da8bf619c3.png)

2021-11-15 07:27 UTC, skyporter requested changes

2021-11-15 07:27 UTC, skyporter commented on Gemfile.lock
> +   2.2.29
https://github.com/catima/catima/pull/383#discussion_r748056321

2021-11-15 07:27 UTC, skyporter commented on app/helpers/fields_helper.rb
> +    "#{field.class.name}Presenter".constantize.new(self, item, field, options, @current_user)
je pense qu'il faut plutot utiliser `current_user` meme si je vois aussi des bouts de cote avec la variable memoize.

Autre point, a mon avis, cette méthode `current_user` est deja disponible dans le présenter et il n'y a pas besoin de la passer en params

2021-11-15 07:27 UTC, skyporter commented on app/models/field.rb
> +  def csv_value(it, current_user= false)
```suggestion
  def csv_value(it, current_user=false)
```

2021-11-15 07:27 UTC, skyporter commented on app/models/field/compound.rb
> +
```suggestion
```

2021-11-15 07:27 UTC, skyporter commented on app/presenters/field/editor_presenter.rb
> +      ].join(' ')
pourquoi ne plus rendre `fields/editor` ?

2021-11-15 07:27 UTC, skyporter commented on app/models/field/compound.rb
> +    Field::CompoundPresenter.new(ApplicationController.new, item, self, {}, current_user).value.to_s
je suis pas sur que ce soit une bonne idée ca. Un presenter c'est pour aider dans le rendu de la vue, du coup tous les helpers de vue sont dispo alors que dans un model tu ne dispo pas de ca.

Pour moi le présenter et la méthode csv_value doivent toutes les 2 appeler une meme méthode du model field (genre `def render_template(item:, user:, etc.)`) qui retourne son contenu avec en paramètres tous ce qu'il y a besoin pour rendre ce contenu.

2021-11-15 07:27 UTC, skyporter commented on app/views/catalog_admin/fields/_compound_option_inputs.html.erb
> +        <% end %>" id="<%= l %>">
```suggestion
      <div id="<%= l %>" role="tabpanel" class="tab-pane <%= "active" if i == 0 %>">
```

2021-11-15 08:52 UTC, abstracts33d commented on app/helpers/fields_helper.rb
> +    "#{field.class.name}Presenter".constantize.new(self, item, field, options, @current_user)
vu avec lucas les fields eux memes utilisent les presenters pour recuperer leurs values

2021-11-15 10:08 UTC, skyporter requested changes

2021-11-15 10:08 UTC, skyporter commented on app/models/field/date_time.rb
> +  def csv_value(item, current_user=false)
est-ce qu'on voudrait pas plutot passer ca a `nil` ce serait plus propre (false <-> true, alors que nil <-> object)

2021-11-15 10:08 UTC, skyporter commented on app/presenters/field/compound_presenter.rb
> +    displayable_fields = displayable_fields.select { |fld| fld.displayable_to_user?(@current_user) } if @current_user
vu qu'il y un helper, appel `current_user` plutot que `@current_user`

2021-11-15 10:08 UTC, skyporter commented on app/presenters/field/compound_presenter.rb
> +    displayable_fields = displayable_fields.select { |fld| fld.displayable_to_user?(@current_user) } if @current_user
je comprend pas comment ca peut marcher, car 1 ligne plus haut tu fait un `map` qui renvoi un string... donc ici `displayable_fields` devrait contenir un array de string, et du coup la méthode `displayable_to_user?` devrait planter non ?

2021-11-15 10:08 UTC, skyporter commented on app/presenters/field/compound_presenter.rb
> +    displayable_fields = @item.fields.where(slug: local_tpl.gsub('&nbsp', ' ').to_enum(:scan, /(\{\{.*?\}\})/i).map { |m,| m.gsub('{', '').gsub('}', '') })
la convention veut que si un params n'est pas utilisé dans un each, map, etc, alors on met `_` => `.map { |m,| `=> `.map { |m, _| `

2021-11-15 10:08 UTC, skyporter commented on app/presenters/field/compound_presenter.rb
> +    local_tpl = tpl[I18n.locale.to_s] || ''
plutot que 2 variables, dont 1 qui sert que 1 fois et l'autre qui contient un nom abrégé:

```suggestion
    template = JSON.parse(field.template)[I18n.locale.to_s] || ''
```

(tpl ca veut bien dire template ??)

2021-11-15 10:08 UTC, skyporter commented on app/presenters/field/compound_presenter.rb
> +      local_tpl = local_tpl.gsub('{{' + field.slug + '}}', presenter.value || '')
https://github.com/rubocop/ruby-style-guide#string-interpolation

2021-11-17 08:38 UTC, abstracts33d commented on app/presenters/field/compound_presenter.rb
> +    displayable_fields = displayable_fields.select { |fld| fld.displayable_to_user?(@current_user) } if @current_user
`@item.fields.where(slug: local_tpl.gsub('&nbsp', ' ').to_enum(:scan, /(\{\{.*?\}\})/i).map { |m,| m.gsub('{', '').gsub('}', '') }) ` renvoie une AR (le map sert juste a gsub pour obtenir les slugs des fields) (cette manip est necessaire pour authoriser la recursion)

2021-11-17 09:23 UTC, abstracts33d commented on app/models/field/compound.rb
> +    Field::CompoundPresenter.new(ApplicationController.new, item, self, {}, current_user).value.to_s
ne fonctionne pas avec la structure existante

2021-11-17 09:26 UTC, abstracts33d commented on app/presenters/field/editor_presenter.rb
> +      ].join(' ')
pour la compatibilité avec le field composé

2021-11-17 12:16 UTC, skyporter commented on app/presenters/field/compound_presenter.rb
> +    displayable_fields = displayable_fields.select { |fld| fld.displayable_to_user?(@current_user) } if @current_user
juste, j'avais pas vu la ")" finale et donc effectivement le map est dans le "where" et non pas au dehors... ok

2021-11-17 13:05 UTC, abstracts33d commented on Gemfile.lock
> +   2.2.29
yes

2021-11-17 13:06 UTC, abstracts33d commented on app/views/catalog_admin/fields/_compound_option_inputs.html.erb
> +        <% end %>" id="<%= l %>">
yes

2021-11-17 13:07 UTC, abstracts33d commented on app/presenters/field/compound_presenter.rb
> +    displayable_fields = @item.fields.where(slug: local_tpl.gsub('&nbsp', ' ').to_enum(:scan, /(\{\{.*?\}\})/i).map { |m,| m.gsub('{', '').gsub('}', '') })
yes

2021-11-17 13:11 UTC, abstracts33d commented on app/presenters/field/compound_presenter.rb
> +    local_tpl = tpl[I18n.locale.to_s] || ''
yes repris de le exemple present dans catima remplacé par local_template

2021-11-17 13:12 UTC, abstracts33d commented on app/presenters/field/compound_presenter.rb
> +      local_tpl = local_tpl.gsub('{{' + field.slug + '}}', presenter.value || '')
yes

2021-12-03 06:45 UTC, skyporter commented on app/presenters/field/compound_presenter.rb
> +    form.text_field(method, input_defaults(options).reverse_merge(:help => help, :value => field.template, :readonly => true))
```suggestion
    form.text_field(method, input_defaults(options).reverse_merge(help: help, value: field.template, readonly: true))
```

2021-12-03 06:45 UTC, skyporter commented on app/presenters/field/compound_presenter.rb
> +
```suggestion
```

2021-12-03 06:46 UTC, skyporter commented on app/views/catalog_admin/fields/_compound_option_inputs.html.erb
> +
```suggestion
  <%= f.hidden_field(:template, value: f.object.template || JSON.dump(@field.item_type.catalog.valid_locales.map { |e| [e, ''] }.to_h)) %>
```

2021-12-03 06:47 UTC, skyporter commented on app/views/catalog_admin/fields/_compound_option_inputs.html.erb
> +            :fields => @field.item_type.fields.reject { |f| f.id == @field.id || (!f.human_readable? && !f.is_a?(Field::Compound)) }.map { |f| {slug: f.slug, name: f.name, type: f.type[7..-1]} }
```suggestion
            contentRef: "field_template",
            locale: l,
            noItemField: true,
            fields: @field.item_type.fields.reject { |f| f.id == @field.id || (!f.human_readable? && !f.is_a?(Field::Compound)) }.map { |f| {slug: f.slug, name: f.name, type: f.type[7..-1]} }
```

2021-12-03 06:48 UTC, skyporter approved these changes

2021-12-03 10:55 UTC, lucaguindani commented
Quelques remarques/questions avant de tester le champ.

- https://user-images.githubusercontent.com/16547134/140530682-ab99386f-4f69-4bea-91d6-25e031eb915a.png
Il faudrait modifier l'affichage du champ composé en mode édition:
-- Il faudrait afficher un champ readonly PAR langue utilisée dans le catalogue, dans le style d'un champ texte (https://cln.sh/y3N4dm). Les utilisateurs ne vont pas êtres capables d'interpréter du json.
-- Il faudrait strip l'html, le but est de retrouver l'affichage de l'éditeur WYSIWYG. Les utilisateurs dans leur grande majorité n'ont pas de notion d'html.

- https://github.com/catima/catima/pull/390/files#diff-979c7672b009a0c1b8b135d006b1ed7aa167fa320588ce7e1cdd262e4d8433abR1
Avez-vous testé l'affichage (ou plutôt le non affichage) si l'option "Afficher les champs vides" n'est pas activé ?

- https://github.com/catima/catima/pull/390/files#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fR24
Quelle est l'utilité de cette dépendance ?

2021-12-06 10:35 UTC, abstracts33d commented
> Quelques remarques/questions avant de tester le champ.
> 
> * https://user-images.githubusercontent.com/16547134/140530682-ab99386f-4f69-4bea-91d6-25e031eb915a.png
>   Il faudrait modifier l'affichage du champ composé en mode édition:
>   -- Il faudrait afficher un champ readonly PAR langue utilisée dans le catalogue, dans le style d'un champ texte (https://cln.sh/y3N4dm). Les utilisateurs ne vont pas êtres capables d'interpréter du json.
>   -- Il faudrait strip l'html, le but est de retrouver l'affichage de l'éditeur WYSIWYG. Les utilisateurs dans leur grande majorité n'ont pas de notion d'html.
> * https://github.com/catima/catima/pull/390/files#diff-979c7672b009a0c1b8b135d006b1ed7aa167fa320588ce7e1cdd262e4d8433abR1
>   Avez-vous testé l'affichage (ou plutôt le non affichage) si l'option "Afficher les champs vides" n'est pas activé ?
> * https://github.com/catima/catima/pull/390/files#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fR24
>   Quelle est l'utilité de cette dépendance ?

1.  la modification a été effectuée (oublis lors des devs)
![image](https://user-images.githubusercontent.com/16547134/144831386-24c3c909-9ff1-482b-9fda-c315fd12e619.png)

2. cela a été testé et est fonctionnel
3. la dépendance semble avoir été ajoutée automatiquement et ne semble pas nécéssaire

2021-12-06 15:54 UTC, lucaguindani commented on app/models/field/compound.rb
> +    "VARCHAR(512)"
Comme le champ composé est utilisé avec un éditeur de texte enrichi, je pense qu'un type _TEXT_ est plus approprié pour le sql_type. Ce type de champ peut contenir plus de 512 caractères ce qui risque donc de poser problème lors d'un export sql.

2021-12-08 10:16 UTC, merged