#179866864 Update ItemList Container
catima/catima pull request #398
Opened 2021-12-15 13:54 UTC by abstracts33d

![image](https://user-images.githubusercontent.com/16547134/146198762-5d1d8af1-d5b1-4fc1-8683-a6d785acda62.png)
![image](https://user-images.githubusercontent.com/16547134/146198892-81c017dc-b037-46b5-b64a-def9f9cbb47c.png)

2021-12-17 15:09 UTC, skyporter requested changes

2021-12-17 15:09 UTC, skyporter commented on app/models/item_list/filter.rb
> +  end
je suis pas sur que c'est une bonne idée que d'override l'existante méthode `def items` , ce serait mieux de faire une méthode dédiée non ?

2021-12-17 15:09 UTC, skyporter commented on app/presenters/field/date_time_presenter.rb
> +    format_str = format.chars.reject { |v| dt[v].blank? }.join
```suggestion
    format_str = (format || field.format).chars.reject { |v| dt[v].blank? }.join
```

2021-12-17 15:09 UTC, skyporter commented on app/views/catalog_admin/containers/_item_list_inputs.html.erb
> +         class="<%= ('d-none' if ((f.object.style != 'timeline') || !f.object&.filterable_field_id.present? || !Field.find(f.object&.filterable_field_id).is_a?(Field::DateTime))) %>">
au lieu de `Field.find(f.object&.filterable_field_id)` ca devrait plutot etre le model qui a une méthode `def filterable_field` qui fait ce "find"

2021-12-17 15:09 UTC, skyporter commented on app/views/catalog_admin/containers/item_list/filterable_field_select_options.html.erb
> +<%= options_for_select(@item_type.fields.map{|f| [f.name, f.id]} ) %>
```suggestion
<%= options_for_select(@item_type.fields.map { |f| [f.name, f.id] }) %>
```

2021-12-17 15:09 UTC, skyporter commented on app/views/items/_timeline.html.erb
> +  url: [page_path(@page), "/#{@container.id}/items/?style=timeline", params[:sort_direction] ? "&sort_direction=#{params[:sort_direction]}" : ""].join(""),
```suggestion
  url: [page_path(@page), "/#{@container.id}/items/?style=timeline", params[:sort_direction] ? "&sort_direction=#{params[:sort_direction]}" : ""].join,
```

2021-12-17 15:09 UTC, skyporter commented on app/views/pages/_content.html.erb
> +  <% @container = c %>
assigner une variable global dans une vue c'est pas vraiment une bonne idée, pour débugger c'est l'enfer.

2021-12-20 10:02 UTC, abstracts33d commented on app/helpers/catalog_admin/containers_helper.rb
> +      Field::DateTime::FORMATS.map{ |f| [f.to_s, f.to_s] },
yes

2021-12-20 10:05 UTC, abstracts33d commented on app/helpers/catalog_admin/containers_helper.rb
> +    )
yes

2021-12-20 10:06 UTC, abstracts33d commented on app/presenters/field/date_time_presenter.rb
> +    format_str = format.chars.reject { |v| dt[v].blank? }.join
yes

2021-12-20 10:08 UTC, abstracts33d commented on app/views/catalog_admin/containers/_item_list_inputs.html.erb
> +         class="<%= ('d-none' if ((f.object.style != 'timeline') || !f.object&.filterable_field_id.present? || !Field.find(f.object&.filterable_field_id).is_a?(Field::DateTime))) %>">
yes

2021-12-20 10:16 UTC, abstracts33d commented on app/views/pages/_content.html.erb
> +  <% @container = c %>
yes

2021-12-20 10:16 UTC, abstracts33d commented on app/views/catalog_admin/containers/item_list/filterable_field_select_options.html.erb
> +<%= options_for_select(@item_type.fields.map{|f| [f.name, f.id]} ) %>
yes

2021-12-20 10:19 UTC, abstracts33d commented on app/javascript/components/Timeline/components/Timeline.jsx
> +    console.log(idx)
yes

2021-12-20 10:19 UTC, abstracts33d commented on app/javascript/components/Timeline/components/Timeline.jsx
> +          {/*{renderItemGroups(groupedItems)}*/}
yes

2021-12-20 10:19 UTC, abstracts33d commented on app/models/field/date_time.rb
> +  def value_as_array(item, format: "YMDhms" )
yes

2021-12-20 10:20 UTC, abstracts33d commented on app/models/field/date_time.rb
> +    format.each_char{|c| defaults[c] = "" }
yes

2021-12-20 13:33 UTC, abstracts33d commented on app/controllers/catalog_admin/pages_controller.rb
> +  skip_before_action :verify_authenticity_token, only: [:filterable_field_select_options, :field_format_select_options]
comme on est  dans du react je peut faire ca dans le react et ca fonctionne mais impossible de retirer le protect_from_forgery :except => [:update_positions]  sans modifications supplémentaires

2021-12-20 13:34 UTC, abstracts33d commented on app/models/item_list/filter.rb
> +  end
impossible car trop encapsulé mais pas de problèmes avec l override

2021-12-20 13:37 UTC, abstracts33d commented on app/helpers/catalog_admin/containers_helper.rb
> +    item_type = form.object.item_type.nil? ?  nil : ItemType.find(form.object.item_type)
entraine trop de modifications exterieures (code ancien)

2021-12-20 13:45 UTC, abstracts33d commented on app/controllers/pages_controller.rb
>    end
moved to helpers

2021-12-20 13:46 UTC, abstracts33d commented on app/helpers/catalog_admin/containers_helper.rb
> +    item_type = form.object.item_type.empty? ?  nil : ItemType.find(form.object.item_type)
yes nécésaire item_type provient de code ancien

2021-12-20 13:52 UTC, abstracts33d commented on app/controllers/catalog_admin/pages_controller.rb
> +    @item_type = ItemType.find(params[:item_type_id])
yes pour 1 mais pas de relation directe pour fields et catalog (field field_set item_type catalog) et non scopé partout ailleur

2021-12-20 17:46 UTC, skyporter commented on app/controllers/catalog_admin/pages_controller.rb
> +    @item_type = ItemType.find(params[:item_type_id])
ok, si c'est comme ca partout ailleurs on fait donc pareil

2021-12-20 17:46 UTC, skyporter commented on app/helpers/catalog_admin/containers_helper.rb
> +    item_type = form.object.item_type.empty? ?  nil : ItemType.find(form.object.item_type)
ah bon ok, c'est un peu moche mais si c'est comme ca historiquement on laisse aini

2021-12-20 17:46 UTC, skyporter commented on app/controllers/catalog_admin/pages_controller.rb
> +  skip_before_action :verify_authenticity_token, only: [:filterable_field_select_options, :field_format_select_options]
ok merci

2021-12-20 17:48 UTC, skyporter commented on app/models/item_list/filter.rb
> +  end
ok, dommage.

2021-12-20 17:51 UTC, skyporter commented on app/javascript/components/Timeline/components/Timeline.jsx
> +    axios.defaults.headers.common["X-Requested-With"] = 'XMLHttpRequest';
tu pourrais plutot faire une seul fois dans packs/application.js ?

2021-12-21 08:25 UTC, abstracts33d commented on app/javascript/components/Timeline/components/Timeline.jsx
> +    axios.defaults.headers.common["X-Requested-With"] = 'XMLHttpRequest';
non je ne pense pas c est pas la meme instance react doit faire ses imports lui meme

2021-12-21 10:00 UTC, abstracts33d commented on app/javascript/components/Timeline/components/Timeline.jsx
> +    axios.defaults.headers.common["X-Requested-With"] = 'XMLHttpRequest';
non fonctionnel

2021-12-22 11:28 UTC, skyporter commented on app/controllers/items_controller.rb
> +    # params.permit!
commentaire a supprimer non ?

2021-12-22 11:28 UTC, skyporter commented on app/controllers/items_controller.rb
> +    # params.permit!
la méthode devrait etre ainsi 
```
  def show
    @item = item_type.public_items.find(params[:id]).behaving_as_type
  rescue ActiveRecord::RecordNotFound => e
    @item_type = item_type
    @item_id = params[:id]
    render 'missing'
  end
```

2021-12-23 09:20 UTC, abstracts33d commented on app/controllers/items_controller.rb
> +    # params.permit!
yes

2022-01-18 08:56 UTC, skyporter approved these changes

2022-01-18 09:44 UTC, merged