Suggestions
catima/catima pull request #403
Opened 2022-01-14 09:01 UTC by abstracts33d

![image](https://user-images.githubusercontent.com/16547134/149483964-cada4e61-7a46-43f7-bd31-631dfd85378b.png)
![image](https://user-images.githubusercontent.com/16547134/149484041-822509ca-e513-4a54-a5af-a7d9cc9ea3ab.png)
![image](https://user-images.githubusercontent.com/16547134/149484124-17521e3e-6331-47b5-b586-62f5bbfde7e2.png)

2022-01-14 12:32 UTC, skyporter requested changes

2022-01-14 12:32 UTC, skyporter commented on app/controllers/suggestions_controller.rb
> +  helper_method :item_type
je ne suis pas sur que c'est une bonne idée de faire un "attr_reader" dans un controller, autant directement utiliser la variable fait dans le find_XXX

2022-01-14 12:32 UTC, skyporter commented on app/javascript/packs/controllers/toggle_display_controller.js
> +    console.log()
```suggestion
```

2022-01-14 12:32 UTC, skyporter commented on app/mailers/suggestions_mailer.rb
> +
```suggestion
  helper :fields
  
  def send_request(receiver, suggestion)
    @suggestion = suggestion
```

2022-01-14 12:32 UTC, skyporter commented on app/mailers/suggestions_mailer.rb
> +    I18n.locale = I18n.default_locale
je suis pas trop sur de comprendre l'utilité de ce ensure ici, tu change la locale dans le template d'email ?

2022-01-14 12:32 UTC, skyporter commented on app/models/item.rb
> +  has_many :suggestions, :dependent => :destroy
```suggestion
  has_many :suggestions, dependent: :destroy
```

2022-01-14 12:32 UTC, skyporter commented on app/models/item_type.rb
> +  has_many :suggestions, :dependent => :destroy
```suggestion
  has_many :suggestions, dependent: :destroy
```

2022-01-14 12:32 UTC, skyporter commented on app/views/api/v3/catalog/shared/suggestions.json.jbuilder
> +    json.processed_at suggestion.processed_at? ? I18n.l(suggestion.processed_at) : nil
une api ne doit pas formatter les date et datetime

```suggestion
    json.processed_at suggestion.processed_at
```

2022-01-14 12:32 UTC, skyporter commented on app/views/api/v3/catalog/shared/suggestions.json.jbuilder
> +    json.content suggestion.content
si les key du json = nom des champs, alors considère faire tout ca en 1 ligne:
```
json.(suggestion, :id, :catalog_id, etc.)
```

2022-01-14 12:32 UTC, skyporter commented on app/views/catalog_admin/shared/_suggestions.html.erb
> +
```suggestion
```

2022-01-14 12:32 UTC, skyporter commented on config/locales/app/en.yml
> +    body: "Suggestion : %{suggestion_content}"
```suggestion
    body: "Suggestion: %{suggestion_content}"
```

2022-01-14 12:32 UTC, skyporter commented on config/locales/app/fr.yml
> +    user: "Utilisateur: %{user}"
```suggestion
    content: "Contenu : %{content}"
    catalog: "Catalogue : %{catalog}"
    item_type: "Item Type : %{item_type}"
    item: "Item : %{item}"
    user: "Utilisateur : %{user}"
```

2022-01-14 12:32 UTC, skyporter commented on app/views/catalog_admin/item_types/_common_form_fields.html.erb
> +      <%= f.email_field(:suggestion_email) %>
ne semble pas etre traduit... 

d'ailleurs ce serait mieux d'ajouter les traductions des fields dans activerecord plutot que ici (fait ca uniquement pour les champs nouvellement ajoutés)

2022-01-14 12:32 UTC, skyporter commented on db/migrate/20220112102223_create_suggestions.rb
> +      t.belongs_to :item_type, index: true, foreign_key: true
faut ajouter `null: false` pour ces 3 relation (Default = true)

2022-01-14 12:32 UTC, skyporter commented on db/migrate/20220112102223_create_suggestions.rb
> +      t.belongs_to :user, index: true, foreign_key: true, optional: true
"optional: true" ca n'existe pas... (https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_reference)

par default c'est deja `null: true` donc tu peux virer ca

2022-01-14 13:03 UTC, abstracts33d commented on app/controllers/suggestions_controller.rb
> +  helper_method :item_type
yes fais comme ca dans d autres controlleurs

2022-01-14 13:06 UTC, skyporter commented
Ah bon d’accord, on laisse comme ca alors

> Le 14 janv. 2022 à 14:05, s33d ***@***.***> a écrit :
> 
> 
> @abstracts33d commented on this pull request.
> 
> In app/mailers/suggestions_mailer.rb <https://github.com/catima/catima/pull/403#discussion_r784827020>:
> 
> > @@ -0,0 +1,15 @@
> +class SuggestionsMailer < ApplicationMailer
> +  helper :fields
> +  def send_request(receiver, suggestion)
> +    @suggestion = suggestion
> +
> +    mail(
> +      :subject => "[Catima] - #{t('suggestions_mailer.subject')}",
> +      :to => receiver,
> +      :from => ENV['MAIL_SENDER'],
> +      :template_name => "suggestion"
> +    )
> +  ensure
> +    I18n.locale = I18n.default_locale
> fais de cette maniere dans tt les mailers
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/catima/catima/pull/403#discussion_r784827020>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AADGAGWYNN6SCUU6TNJV73TUWANRFANCNFSM5L6HCJAA>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
> You are receiving this because you commented.
>

2022-01-14 13:07 UTC, abstracts33d commented on app/views/api/v3/catalog/shared/suggestions.json.jbuilder
> +    json.content suggestion.content
yes

2022-01-14 13:11 UTC, abstracts33d commented on app/views/catalog_admin/item_types/_common_form_fields.html.erb
> +      <%= f.email_field(:suggestion_email) %>
yes

2022-01-14 13:11 UTC, abstracts33d commented on db/migrate/20220112102223_create_suggestions.rb
> +      t.belongs_to :item_type, index: true, foreign_key: true
yes

2022-01-14 13:12 UTC, abstracts33d commented on db/migrate/20220112102223_create_suggestions.rb
> +      t.belongs_to :user, index: true, foreign_key: true, optional: true
yes

2022-01-14 13:26 UTC, abstracts33d commented on app/controllers/suggestions_controller.rb
> +    redirect_to edit_catalog_admin_item_path(id: @item.id)
non fonctionnel

2022-01-14 13:27 UTC, abstracts33d commented on app/controllers/suggestions_controller.rb
> +    @suggestion.delete
yes

2022-01-18 08:53 UTC, skyporter commented on app/controllers/catalog_admin/suggestions_controller.rb
> +      catalog.item_types.where(:slug => params[:item_type_slug]).first!
```suggestion
    @item_type = catalog.item_types.find_by(slug: params[:item_type_slug])
```
(non testé mais ca devrait passer)

2022-01-18 08:55 UTC, skyporter commented on app/controllers/suggestions_controller.rb
> +      catalog.item_types.where(:slug => params[:item_type_slug]).first!
meme comment que https://github.com/catima/catima/pull/403/files#r786531012

2022-01-21 13:12 UTC, abstracts33d commented on app/controllers/catalog_admin/suggestions_controller.rb
> +      catalog.item_types.where(:slug => params[:item_type_slug]).first!
yes

2022-01-21 13:12 UTC, abstracts33d commented on app/controllers/suggestions_controller.rb
> +      catalog.item_types.where(:slug => params[:item_type_slug]).first!
yes

2022-02-03 13:19 UTC, merged