Timeline CR
catima/catima pull request #413
Opened 2022-01-19 13:45 UTC by abstracts33d

2022-02-17 09:39 UTC, skyporter requested changes

2022-02-17 09:39 UTC, skyporter commented on app/helpers/items_helper.rb
> +
```suggestion
```

2022-02-17 09:39 UTC, skyporter commented on app/javascript/components/Line/components/Line.jsx
> +
```suggestion
```

2022-02-17 09:39 UTC, skyporter commented on app/javascript/components/Line/components/Line.jsx
> +
```suggestion
```

2022-02-17 09:39 UTC, skyporter commented on config/locales/app/en.yml
> +          11: Décembre
est-ce qu'on pourrait plutot utiliser la liste qui existe deja dans `date.numerical_months` plutot que créer une nouvelle liste ?

2022-02-17 09:39 UTC, skyporter commented on config/locales/app/en.yml
> +          11: Décembre
(d'ailleurs ici c'est la version EN et non pas FR)

2022-02-17 09:39 UTC, skyporter commented on test/integration/catalog_admin/items_sort_test.rb
> -
rollback ce changes stp

2022-02-17 09:48 UTC, lucaguindani commented on app/views/items/_line.html.erb
> +  monthNames: I18n.t('catalog_admin.fields.date_time_option_inputs.numerical_months').values,
Si jamais tu n'as pas besoin de passer les locales en params de tes composants react (https://github.com/catima/catima/pull/413/files#diff-56716f5439213b55ccf913760d5ffe5422e461fef778cb61dd4c4d7122cbb10eR12). 

Tu peux directement les utiliser dans le composant via "Translations" (comme par exemple [https://github.com/catima/catima/blob/b9a9ac9c6a84dc4ff43e8ff6a0375d3d83ea7de5/app[…]ipt/components/ThumbnailControl/components/ThumbnailControl.jsx](https://github.com/catima/catima/blob/b9a9ac9c6a84dc4ff43e8ff6a0375d3d83ea7de5/app/javascript/components/ThumbnailControl/components/ThumbnailControl.jsx#L5)). C'est plus propre au niveau du code et plus simple pour toi.

2022-02-18 17:24 UTC, lucaguindani commented on config/locales/app/en.yml
> +          11: Décembre
@skyporter je ne pense pas qu'alourdir le translations.js soit une bonne solution.

Pourquoi ne pas utiliser https://github.com/catima/catima/blob/46e57a85a015ef4146e31ece980fa9ec425caef6/config/locales/app/fr.yml#L732 ?

2022-02-18 17:31 UTC, skyporter commented on config/locales/app/en.yml
> +          11: Décembre
@lucaguindani effectivement j'avais oublié cette traduction, merci.

@abstracts33d stp fait le changement et vire ces nouvelles traductions. Tu m'avais parlé de ne pas savoir comment utiliser cette liste avec key/value pour avoir int/value, voila comment faire :

```ruby
I18n.t("catalog_admin.fields.date_time_option_inputs.months").map.with_index { |(_,v),i| [i + 1, v] }
=> [[1, "January"], [2, "February"], [3, "March"], [4, "April"], [5, "May"], [6, "June"], [7, "July"], [8, "August"], [9, "September"], [10, "October"], [11, "November"], [12, "December"]]
```

2022-02-21 17:17 UTC, skyporter approved these changes

2022-02-23 13:46 UTC, merged