Hide public list view if field is not human readable
catima/catima pull request #484
Opened 2022-12-23 12:45 UTC by daviserez

2023-01-05 14:08 UTC, lucaguindani requested changes

2023-01-05 14:08 UTC, lucaguindani commented on app/helpers/catalog_admin/fields_option_helper.rb
> +  def could_be_human_readable(field)
Transformer en clause de garde avec commentaires

2023-01-05 15:03 UTC, daviserez commented on app/views/catalog_admin/fields/_text_option_inputs.html.erb
> +      style="color: #666;"
J'ai utilisé la classe bootstrap "text-secondary", qui est du #6c757d, la différence est très subtile par rapport à du #666.

<img width="156" alt="image" src="https://user-images.githubusercontent.com/832658/210810956-25f1b00e-bdf0-4e2c-87ff-d3cef961a78f.png">

2023-01-06 08:32 UTC, lucaguindani approved these changes

2023-01-06 08:33 UTC, merged